#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause

# defaults
. /etc/os-release
DEB_DISTRO="${DEB_DISTRO:-$VERSION_CODENAME}"
DEB_ARCH="${DEB_ARCH:-$(dpkg --print-architecture)}"

while getopts a:d:h OPTCHAR; do
  case "$OPTCHAR" in
    a)
      DEB_ARCH="$OPTARG"
      ;;
    d)
      DEB_DISTRO="$OPTARG"
      ;;
    h)
      echo "usage: $0 [-a] [-d]"
      echo "  -a To specify the architecture of the chroot."
      echo "  -d To specify the distribution of the chroot."
      exit
      ;;
    *)
      echo "Error parsing arguments"
      exit 1
      ;;
  esac
done
shift "$((OPTIND - 1))"

echo "Install dependencies"

set -ex

test "$VERSION_CODENAME" = "jammy" && sudo cp "$(dirname "$0")/jammy-sbuild.sources" /etc/apt/sources.list.d/

# install ROS repo for dev tools
sudo apt update && sudo apt install curl -y
export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F'"' '{print $4}')
curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.${UBUNTU_CODENAME:-${VERSION_CODENAME}}_all.deb"
sudo dpkg -i /tmp/ros2-apt-source.deb

sudo apt update

sudo DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends sbuild mmdebstrap distro-info debian-archive-keyring ccache uidmap curl git-lfs

if [ "$DEB_ARCH" != "$(dpkg --print-architecture)" ]; then
  # use qemu to translate architecture
  sudo apt install -y --no-install-recommends qemu-user-static arch-test
  if [ "$VERSION_CODENAME" = "jammy" ]; then
    # manally enable binfmt_misc on Ubuntu 22.04 Docker images
    sudo apt install -y --no-install-recommends binfmt-support
    arch-test "$DEB_ARCH" || sudo update-binfmts --enable
  fi
fi

# development packages
sudo DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends ros-dev-tools

sudo rosdep init

echo "Setup build environment"

mkdir -p "$HOME/.cache/sbuild"
mmdebstrap --variant=buildd --include=apt,ccache,ca-certificates --arch="$DEB_ARCH" \
  --customize-hook='chroot "$1" update-ccache-symlinks' \
  --components=main,universe "$DEB_DISTRO" "$HOME/.cache/sbuild/$DEB_DISTRO-$DEB_ARCH.tar"

ccache --zero-stats --max-size=10.0G

# allow ccache access from sbuild
chmod a+X "$HOME" "$HOME/.cache"
chmod -R a+rwX "$HOME/.cache/ccache"

cat << "EOF" > "$HOME/.sbuildrc"
$build_environment = { "CCACHE_DIR" => "/build/ccache" };
$path = "/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games";
$build_path = "/build/package/";
$dsc_dir = "package";
$unshare_bind_mounts = [ { directory => "$HOME/.cache/ccache", mountpoint => "/build/ccache" } ];
$verbose = 1;
EOF
echo "$SBUILD_CONF" >> "$HOME/.sbuildrc"

test -z "$REPOS_FILE" -a ! -f repo/sources.repos && exit
REPOS_FILE="repo/${REPOS_FILE:-sources.repos}"

echo "Checkout workspace"

mkdir src
vcs import --recursive --input  "$REPOS_FILE" src
